/////////////////////////////////////////////////////////////////////////////////////////////////////////
// This configuration file was generated by the OAT Configurator at https://config.openastrotech.com for
// firmware Latest Official (V1.10.1).
// Save this as Configuration_local.hpp in the folder where you placed the firmware code.
// Unique ConfigKey: FW:O,HS:N,BD:M21,RS:N9,RD:TU,RAP1500:O90:S2:T128:,RMSA3000:V2800:,RT:1,DS:N9,DD:TU,DAP1500:O90:S2:T256:,DMSA3000:V2800:,DT:1,DY:NO,GP:N,LM:N,FC:N,AV:2,ZS:N9,ZD:TU,AP:N,ZAP900:O90:H10:,AH:N

// We live in the Northern Hemisphere
#define NORTHERN_HEMISPHERE 1

// We are using the ESP32 board 

#if defined(BOARD) && BOARD != BOARD_OAE_V1 
#error Selected PIO environment does not match this configuration 
#else 
#define BOARD BOARD_OAE_V1 
#endif 


////////////////////////////////
// RA Stepper configuration 
// See supported stepper values. Change according to the steppers you are using
// Using the NEMA 17, 0.9°/step stepper for RA
#define RA_STEPPER_TYPE STEPPER_TYPE_ENABLE

// Using the TMC2209-UART driver for RA stepper motor
#define RA_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define some RA stepper motor settings
#define RA_MOTOR_CURRENT_RATING       1200 // mA
#define RA_OPERATING_CURRENT_SETTING  80 // %
#define RA_SLEW_MICROSTEPPING         4
#define RA_TRACKING_MICROSTEPPING     256

#define TRACK_ON_BOOT 0

// TMC2209 Stealth Mode (spreadCycle) - When set to 0, tracking is more precise, but noisy (high-pitched sound). When set to 1, they are silent.
#define RA_UART_STEALTH_MODE          0

// Is it going the wrong way?
#define RA_INVERT_DIR  0

// Define some RA stepper motor settings

#define RA_SLEWING_SPEED_DEGREE 3
#define RA_ACCEL_SecToFullSpeed 1  // Seconds to reach full slewing speed
//#define RA_STEPPER_SPEED 4000 

#define RA_STEPPER_SPEED RA_SLEWING_SPEED_DEGREE * (RA_STEPPER_SPR * RA_SLEW_MICROSTEPPING * (RA_WHEEL_CIRCUMFERENCE / (RA_PULLEY_TEETH * GT2_BELT_PITCH)) / 360)  //3525
#define RA_STEPPER_ACCELERATION (RA_STEPPER_SPEED / RA_ACCEL_SecToFullSpeed)

// (RA_STEPPER_SPR * RA_SLEW_MICROSTEPPING *RA_TRANSMISSION ) 360 * deg

// Using the 16 tooth gear (recommended) for RA belt
#define RA_PULLEY_TEETH 16

////////////////////////////////
// DEC Stepper configuration 
// See supported stepper values. Change according to the steppers you are using
// Using the NEMA 17, 0.9°/step stepper for DEC
#define DEC_STEPPER_TYPE STEPPER_TYPE_ENABLE

// Using the TMC2209-UART driver for DEC stepper
#define DEC_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define some DEC stepper motor settings
#define DEC_MOTOR_CURRENT_RATING       2000 // mA
#define DEC_OPERATING_CURRENT_SETTING  60 // %
#define DEC_SLEW_MICROSTEPPING         32
#define DEC_GUIDE_MICROSTEPPING        256

// TMC2209 Stealth Mode (spreadCycle) - When set to 0, tracking is more precise, but noisy (high-pitched sound). When set to 1, they are silent.
#define DEC_UART_STEALTH_MODE          1

// Is it going the wrong way?
#define DEC_INVERT_DIR  0

#define DEC_SLEWING_SPEED_DEGREE RA_SLEWING_SPEED_DEGREE
#define DEC_ACCEL_SecToFullSpeed RA_ACCEL_SecToFullSpeed

#define DEC_STEPPER_SPEED DEC_SLEWING_SPEED_DEGREE * (DEC_STEPPER_SPR * DEC_SLEW_MICROSTEPPING / 360 ) // * (DEC_WHEEL_CIRCUMFERENCE / (DEC_PULLEY_TEETH * GT2_BELT_PITCH)) / 360)
#define DEC_STEPPER_ACCELERATION (DEC_STEPPER_SPEED / DEC_ACCEL_SecToFullSpeed)

////////////////////////////////
// Display configuration 
// Define the type of display we are using. Currently: No display
#define DISPLAY_TYPE DISPLAY_TYPE_NONE

////////////////////////////////
// GPS Addon configuration 
// Define whether we have the GPS addon or not. Currently: No GPS
#define USE_GPS 0


// Using the NEMA 17, 0.9°/step stepper for AZ
#define AZ_STEPPER_TYPE STEPPER_TYPE_ENABLED
#define ALT_STEPPER_TYPE STEPPER_TYPE_ENABLED

// Using the TMC2209-UART driver for AZ stepper motor
#define AZ_DRIVER_TYPE DRIVER_TYPE_A4988_GENERIC 
#define ALT_DRIVER_TYPE DRIVER_TYPE_A4988_GENERIC 

////////////////////////////////
// Digital Level Addon configuration 
// Define whether we have the Digital Level or not. Currently: No Digital Level
#define USE_GYRO_LEVEL 0

#define WIFI_ENABLED 0 

///////////////////////
// Debug settings
#define DEBUG_LEVEL (DEBUG_NONE)
//#define DEBUG_LEVEL (DEBUG_STEPPERS)
//#define configCHECK_FOR_STACK_OVERFLOW 1

///////////////////////
// OAE specific defines

#define OAE

#define DEC_PULLEY_TEETH 1

#define RA_STEPPER_SPR (400 * 9)   // change to (200 * 9) for 1.8° stepper
#define DEC_STEPPER_SPR (200 * 50 * 4.5f)  // change "200" to "400" for 0.9° stepper, change "50" to different value depending on worm gear used


// AZ 
#define AZ_STEPPER_SPR 2048 // 28BYJ-48
#define AZ_MICROSTEPPING 1
#define AZ_STEPPER_SPEED 1200
#define AZ_STEPPER_ACCELERATION 3000

// ALT
#define ALT_STEPPER_SPR 2048    // 28BYJ-48
#define ALT_MICROSTEPPING 1
#define ALT_STEPPER_SPEED 800
#define ALT_STEPPER_ACCELERATION 3000


